# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 48c93a2155ceb7d2e66c7d5c54d734915dd8fd752c76d48181c265b3f0d895056bf41b3027aa84f2533f8d70edb73139f244970ce12afde92b93a80b041b2de1

test:
  secret_key_base: 3f9abecf019ae9ec4beb919142ca0d0a5731bd4f5b3a5fc0a319104a9e5b4de143f2a0e2d5493fd6fcfa9f13e4f756bbc93c0b594070c99ec1424bc5050d917e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
